version: '3.4'

services:
  cas:
    build:
      context: .
      args:
        ENV_TAG: dev
    environment:
      - AWS_ACCOUNT_ID=000000000000
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=.
      - AWS_SECRET_ACCESS_KEY=.
      - AWS_ENDPOINT=http://localstack:4566
      - DB_AWS_ENDPOINT=http://localstack:4566
      - PG_HOST=database
      - PG_PORT=5432
      - PG_USER=root
      - PG_PASSWORD=root
      - PG_DB=anchor_db
      - ENV=dev
    depends_on:
      - localstack
      - database
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - internal

  cas_api:
    image: ceramicnetwork/ceramic-anchor-service:release-candidate
    environment:
      - NODE_ENV=dev
      - APP_MODE=server
      - APP_PORT=8081
      - ANCHOR_CONTROLLER_ENABLED=false
      - ANCHOR_EXPIRATION_PERIOD=0
      - ANCHOR_SCHEDULE_EXPRESSION=0/1 * * * ? *
      - BLOCKCHAIN_CONNECTOR=ethereum
      - CERAMIC_API_URL=http://host.docker.internal:7007
      - ETH_GAS_LIMIT=4712388
      - ETH_GAS_PRICE=100000000000
      - ETH_NETWORK=ganache
      - ETH_RPC_URL=http://ganache:8545
      - ETH_OVERRIDE_GAS_CONFIG=false
      - ETH_WALLET_PK=0xbf873129c72676a8ae3be570c5d6346a5722e7ebac57ed8d08dfd3d1467d6dd6
      - ETH_CONTRACT_ADDRESS=0x663F90C8A3B4dA654e2d23b6564426FEDa684c8F
      - IPFS_API_URL=http://ipfs:5001
      - IPFS_API_TIMEOUT=120000
      - LOG_LEVEL=debug
      - LOG_TO_FILES=true
      - LOG_PATH=/usr/local/var/log
      - MERKLE_DEPTH_LIMIT=0
      - DB_NAME=anchor_db
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - VALIDATE_RECORDS=false
    depends_on:
      - ipfs
      - database
    ports:
      - '8081:8081'
    volumes:
      - './migrations:/cas/migrations'
    networks:
      - internal

  cas_worker:
    build:
      context: ../ceramic-anchor-service
      target: base
    restart: unless-stopped
    environment:
      - NODE_ENV=dev
      - APP_MODE=anchor
      - APP_PORT=8081
      - USE_SMART_CONTRACT_ANCHORS=true
      - USE_QUEUE_BATCHES=true
      - ANCHOR_CONTROLLER_ENABLED=false
      - INCLUDE_BLOCK_INFO_IN_ANCHOR_PROOF=false
      - MERKLE_DEPTH_LIMIT=0
      - MIN_STREAM_COUNT=2
      - IPFS_API_URL=http://ipfs:5001
      - IPFS_PUBSUB_TOPIC=/steph
      - IPFS_API_TIMEOUT=60000
      - IPFS_CONCURRENT_GET_LIMIT=100
      - BLOCKCHAIN_CONNECTOR=ethereum
      - ETH_NETWORK=ganache
      - ETH_OVERRIDE_GAS_CONFIG=false
      - ETH_GAS_LIMIT=6721975
      - ETH_RPC_URL=http://ganache:8545
      - ETH_WALLET_PK=0xbf873129c72676a8ae3be570c5d6346a5722e7ebac57ed8d08dfd3d1467d6dd6
      - ETH_CONTRACT_ADDRESS=0x663F90C8A3B4dA654e2d23b6564426FEDa684c8F
      - LOG_LEVEL=debug
      - LOG_TO_FILES=true
      - LOG_PATH=/usr/local/var/log
      - DB_NAME=anchor_db
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - SQS_QUEUE_URL=http://localstack:4566/000000000000/cas-anchor-dev-batch
      - AWS_ACCOUNT_ID=000000000000
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=.
      - AWS_SECRET_ACCESS_KEY=.
    depends_on:
      - ipfs
      - database
      - localstack
      - cas_api
      - launch_contract
      - ganache
    volumes:
      - './migrations:/cas/migrations'
    networks:
      - internal

  ipfs:
    image: ceramicnetwork/go-ipfs-daemon
    ports:
      - '5001:5001'
    networks:
      - internal

  database:
    image: 'postgres'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=anchor_db
    ports:
      - '5432:5432'
    networks:
      - internal

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - '4563-4584:4563-4584'
      - '8055:8080'
    environment:
      - SERVICES=sqs,dynamodb
    networks:
      - internal

  ganache:
    image: trufflesuite/ganache
    ports:
      - '8545:8545'
    command:
      - "--mnemonic='move sense much taxi wave hurry recall stairs thank brother nut woman' --networkId=5777 --hostname=0.0.0.0 -l=80000000"
    networks:
      - internal

  launch_contract:
    build:
      context: .
      dockerfile: Dockerfile.launchContract
    environment:
      - ETH_RPC_URL=http://ganache:8545
      - ETH_WALLET_PK=0xbf873129c72676a8ae3be570c5d6346a5722e7ebac57ed8d08dfd3d1467d6dd6
    depends_on:
      - ganache
    networks:
      - internal

networks:
  internal:
    driver: bridge
