version: '3.4'

services:
  cas:
    build:
      context: ../go-cas
    container_name: go_cas
    restart: on-failure
    environment:
      - AWS_ACCOUNT_ID=000000000000
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=.
      - AWS_SECRET_ACCESS_KEY=.
      - AWS_ENDPOINT=http://localstack:4566
      - DB_AWS_ENDPOINT=http://localstack:4566
      - PG_HOST=database
      - PG_PORT=5432
      - PG_USER=root
      - PG_PASSWORD=root
      - PG_DB=anchor_db
      - ANCHOR_BATCH_SIZE=4
      - ANCHOR_BATCH_LINGER=5m
    depends_on:
      localstack:
        condition: service_healthy
      database:
        condition: service_healthy
      cas_api:
        condition: service_healthy
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - internal

  cas_worker:
    build:
      context: ../ceramic-anchor-service
      target: base
    restart: unless-stopped
    environment:
      - NODE_ENV=dev
      - APP_MODE=anchor
      - APP_PORT=8081
      - USE_SMART_CONTRACT_ANCHORS=true
      - USE_QUEUE_BATCHES=true
      - ANCHOR_CONTROLLER_ENABLED=false
      - INCLUDE_BLOCK_INFO_IN_ANCHOR_PROOF=false
      - MERKLE_DEPTH_LIMIT=0
      - MIN_STREAM_COUNT=1
      - IPFS_API_URL=http://cas_ipfs:5001
      - IPFS_PUBSUB_TOPIC=/integration-tests-docker
      - IPFS_API_TIMEOUT=60000
      - IPFS_CONCURRENT_GET_LIMIT=100
      - BLOCKCHAIN_CONNECTOR=ethereum
      - ETH_NETWORK=ganache
      - ETH_OVERRIDE_GAS_CONFIG=false
      - ETH_GAS_LIMIT=6721975
      - ETH_RPC_URL=http://ganache:8545
      - ETH_WALLET_PK=0x06dd0990d19001c57eeea6d32e8fdeee40d3945962caf18c18c3930baa5a6ec9
      - ETH_CONTRACT_ADDRESS=0xd3f84cf6be3dd0eb16dc89c972f7a27b441a39f2
      - LOG_LEVEL=debug
      - LOG_TO_FILES=true
      - LOG_PATH=/usr/local/var/log
      - DB_NAME=anchor_db
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - SQS_URL=http://localstack:4566/000000000000/cas-anchor-dev-batch
      - SQS_QUEUE_USE_POLLING=true
      - AWS_ACCOUNT_ID=000000000000
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=.
      - AWS_SECRET_ACCESS_KEY=.
    depends_on:
      localstack:
        condition: service_healthy
      database:
        condition: service_healthy
      cas_ipfs:
        condition: service_healthy
      cas_api:
        condition: service_healthy
      launch_contract:
        condition: service_completed_successfully
    networks:
      - internal
    deploy:
      mode: replicated
      replicas: 1

  cas_api:
    image: ceramicnetwork/ceramic-anchor-service:release-candidate
    container_name: cas_api
    environment:
      - NODE_ENV=dev
      - APP_MODE=server
      - APP_PORT=8081
      - ANCHOR_CONTROLLER_ENABLED=false
      - ANCHOR_EXPIRATION_PERIOD=0
      - ANCHOR_SCHEDULE_EXPRESSION=0/1 * * * ? *
      - BLOCKCHAIN_CONNECTOR=ethereum
      - ETH_GAS_LIMIT=4712388
      - ETH_GAS_PRICE=100000000000
      - ETH_NETWORK=ganache
      - ETH_RPC_URL=http://ganache:8545
      - ETH_OVERRIDE_GAS_CONFIG=false
      - ETH_WALLET_PK=0x06dd0990d19001c57eeea6d32e8fdeee40d3945962caf18c18c3930baa5a6ec9
      - ETH_CONTRACT_ADDRESS=0xd3f84cf6be3dd0eb16dc89c972f7a27b441a39f2
      - IPFS_API_URL=http://cas_ipfs:5001
      - IPFS_API_TIMEOUT=120000
      - LOG_LEVEL=debug
      - LOG_TO_FILES=true
      - LOG_PATH=/usr/local/var/log
      - MERKLE_DEPTH_LIMIT=0
      - DB_NAME=anchor_db
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - VALIDATE_RECORDS=false
    depends_on:
      cas_ipfs:
        condition: service_healthy
      database:
        condition: service_healthy
      launch_contract:
        condition: service_completed_successfully
    ports:
      - '8081:8081'
    networks:
      - internal
    healthcheck:
      test: ['CMD', 'curl', 'http://localhost:8081/api/v0/healthcheck']
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  cas_ipfs:
    image: ceramicnetwork/go-ipfs-daemon
    container_name: cas_ipfs
    ports:
      - '5001:5001'
      - '8111:8011'
    networks:
      - internal

  database:
    image: 'postgres'
    container_name: database
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=anchor_db
    ports:
      - '5432:5432'
    networks:
      - internal
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', '-d', 'anchor_db', '-U', 'root']
      interval: 10s
      timeout: 5s
      retries: 5

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - '4563-4584:4563-4584'
      - '8055:8080'
    environment:
      - SERVICES=sqs,dynamodb
    networks:
      - internal
    healthcheck:
      test:
        - CMD
        - bash
        - -c
        - awslocal dynamodb list-tables
          && awslocal es list-domain-names
          && awslocal s3 ls
          && awslocal sqs list-queues
      interval: 5s
      timeout: 10s
      start_period: 10s

  ganache:
    image: trufflesuite/ganache
    container_name: ganache
    ports:
      - '8545:8545'
    entrypoint:
      - node
      - /app/dist/node/cli.js
      - --miner.blockTime=5
      - --mnemonic='move sense much taxi wave hurry recall stairs thank brother nut woman'
      - --networkId=5777
      - --hostname=0.0.0.0
      - -l=80000000
    networks:
      - internal

  launch_contract:
    build:
      context: .
      dockerfile: Dockerfile.launchContract
    container_name: contract
    environment:
      - ETH_RPC_URL=http://ganache:8545
      - ETH_WALLET_PK=0x06dd0990d19001c57eeea6d32e8fdeee40d3945962caf18c18c3930baa5a6ec9
    depends_on:
      - ganache
    networks:
      - internal

  remote_ceramic:
    image: ceramicnetwork/js-ceramic:latest
    container_name: remote_ceramic
    ports:
      - 7007:7007
      - 4011:4011
      - 4012:4012
      - 5011:5011
      - 9011:9011
      - 8011:8011
    depends_on:
      cas_api:
        condition: service_healthy
      ganache:
        condition: service_started
    entrypoint: ''
    command: >
      /bin/bash -c "
        cd packages/cli
        ./bin/ceramic.js daemon --port 7007 --network local --anchor-service-api http://cas_api:8081 --ethereum-rpc http://ganache:8545 --pubsubTopic /integration-tests-docker
      "
    healthcheck:
      test: ['CMD', 'curl', 'http://localhost:7007']
      interval: 20s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - internal

networks:
  internal:
    driver: bridge
